# Generated by Django 6.0.2 on 2026-03-02 19:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_supabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAgendaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_plataforma', models.TimeField(default=datetime.time(6, 0))),
                ('hora_fin_plataforma', models.TimeField(default=datetime.time(18, 0))),
                ('duracion_sesion_minutos', models.PositiveIntegerField(default=45)),
                ('descanso_minutos', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Configuración Global de Agenda',
                'verbose_name_plural': 'Configuraciones Globales de Agenda',
            },
        ),
        migrations.CreateModel(
            name='TherapistBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='auth_supabase.profilemodel')),
            ],
            options={
                'db_table': 'agenda_therapist_block',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to='auth_supabase.profilemodel')),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_therapist', to='auth_supabase.profilemodel')),
            ],
            options={
                'db_table': 'agenda_appointment',
                'indexes': [models.Index(fields=['start_datetime', 'end_datetime'], name='agenda_appo_start_d_b113b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TherapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='auth_supabase.profilemodel')),
            ],
            options={
                'db_table': 'agenda_therapist_availability',
                'unique_together': {('therapist', 'day_of_week')},
            },
        ),
    ]
