# Generated by Django 6.0.2 on 2026-03-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADO', 'Reservado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20),
        ),
    ]
