# Generated by Django 6.0.2 on 2026-03-07 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("client", "Client"), ("therapist", "Therapist")],
                        max_length=20,
                    ),
                ),
                (
                    "external_auth_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("specialty", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "session_price",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_supabase_profile",
            },
        ),
    ]
